# Site settings
title: A-B-Z
email: mail@a-b-z.co
description: ● A-B-Z-TXT is a school for 21st century typography. InterAccess in Toronto. August 17–20, 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://a-b-z.co" # the base hostname & protocol for your site
twitter_username: abz_co

# Build settings
markdown: kramdown

# Asset compiling
sass:
  style: :compressed

# Exclude from build
exclude: [vendor, Gemfile, Gemfile.lock, node_modules, package.json, webpack.config.js]

# Speakers List
collections:
  program_lectures:
    output: false
  program_lectures_workshops:
    output: false
  program_masterclass:
    output: false
