# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A-B-Z
email: mail@a-b-z.co
description: TORONTO-INTERACCESS. AUG-18–21-2016. A-SCHOOL-FOR-21st-CENTURY-TYPOGRAPHY.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://a-b-z.co" # the base hostname & protocol for your site
twitter_username: abz_co

# Build settings
markdown: kramdown

# Asset compiling
sass:
  style: :compressed

# Exclude from build
exclude: [Gemfile, Gemfile.lock, node_modules, speakers, package.json, webpack.config.js, webpack.config.production.js]

# Speakers List
collections:
  program_lectures:
    label: Lectures
    output: false
  program_lectures_workshops:
    output: false
  program_masterclass:
    label: 1-Day-Masterclasses
    output: false
  footnotes:
    output: false